import Head from 'next/head'
import { ActiveMenu, Menu } from '@/components/Menu'
import { useState } from 'react'
import { Webhooks } from '@/components/Webhooks';
import { Registers } from '@/components/Registers';

export default function Home() {

  const [active, setActive] = useState<ActiveMenu>(ActiveMenu.webhooks);

  return (
    <>
      <Head>
        <title>POC Pipefy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu active={active} setActive={setActive}/>
        {active === ActiveMenu.webhooks && <Webhooks /> }
        {active === ActiveMenu.registros && <Registers /> }
      </main>
    </>
  )
}
